package com.catalisa.iSchool.enums;

public enum NomesCursos {
    SISTEMAS_DA_INFORMACAO,
    ENGENHARIA_DA_COMPUTACAO,
    ANALISE_E_DESENVOLVIMENTO_DE_SISTEMAS,
    CIENCIA_DA_COMPUTACAO,
    CIENCIA_DE_DADOS,
    SEGURANCA_DA_INFORMACAO
}
